
-- -------------------------------------------------------------------
--  IVA SMART BILLING — SHOP DATA PLANE UPDATE V7 
--  Run this ONCE in the INDIVIDUAL SHOP Supabase SQL Editor.
-- -------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    gst DECIMAL(5,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: We use BIGINT for id because in SQLite it's INTEGER PRIMARY KEY AUTOINCREMENT (which corresponds to BIGINT)
-- We don't use SERIAL because the ID is generated by the local SQLite database and synced up.

-- Add RLS Policies
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users on categories" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users on categories" ON public.categories FOR UPDATE USING (true);

-- Adjust products table to reference categories name
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category_name TEXT;

